import type { Demand, InboxItem } from './types';

export const demands: Demand[] = [
  {
    id: 'D2D-2025-001',
    name: 'Customer Portal Redesign',
    lead: 'Sara Al Hashimi',
    submitted: '15/01/25',
    goLive: '30/06/25',
    status: 'b-rv',
    statusLabel: 'Review In Progress',
    stage: 'Review',
  },
  {
    id: 'D2D-2025-002',
    name: 'SAP S/4HANA Finance Module Upgrade',
    lead: 'Fatima Al Zaabi',
    submitted: '20/01/25',
    goLive: '30/09/25',
    status: 'b-pa',
    statusLabel: 'Pending Approval',
    stage: 'Approval',
  },
  {
    id: 'D2D-2025-003',
    name: 'Smart Grid Monitoring Platform',
    lead: 'Unassigned',
    submitted: '01/02/25',
    goLive: '31/12/25',
    status: 'b-rt',
    statusLabel: 'Returned',
    stage: 'Returned',
  },
  {
    id: 'D2D-2025-004',
    name: 'AI Chatbot for Internal Helpdesk',
    lead: 'Omar Al Falasi',
    submitted: '25/01/25',
    goLive: '15/04/25',
    status: 'b-gl',
    statusLabel: 'Go Live Preparation',
    stage: 'Progress',
  },
  {
    id: 'D2D-2025-005',
    name: 'Vendor Management System',
    lead: 'Amina Al Dhaheri',
    submitted: '10/12/24',
    goLive: '31/08/25',
    status: 'b-ip',
    statusLabel: 'In Progress',
    stage: 'Progress',
  },
  {
    id: 'D2D-2025-006',
    name: 'SAP HR Leave Management Enhancement',
    lead: 'Unassigned',
    submitted: '05/02/25',
    goLive: '31/05/25',
    status: 'b-ap',
    statusLabel: 'Approval In Progress',
    stage: 'Approval',
  },
  {
    id: 'D2D-2025-007',
    name: 'Mobile Field Inspection App',
    lead: 'Sara Al Hashimi',
    submitted: '10/01/25',
    goLive: '30/04/25',
    status: 'b-ip',
    statusLabel: 'In Progress',
    stage: 'Progress',
  },
  {
    id: 'D2D-2025-008',
    name: 'Data Warehouse Modernization',
    lead: 'Omar Al Falasi',
    submitted: '05/01/25',
    goLive: '31/03/26',
    status: 'b-ap',
    statusLabel: 'Approval In Progress',
    stage: 'Approval',
  },
  {
    id: 'D2D-2025-009',
    name: 'Employee Self-Service Portal',
    lead: 'Khalid Al Mansoori',
    submitted: '12/02/25',
    goLive: '30/07/25',
    status: 'b-dr',
    statusLabel: 'Draft',
    stage: 'Draft',
  },
  {
    id: 'D2D-2025-010',
    name: 'IoT Asset Management System',
    lead: 'Hessa Al Mehairi',
    submitted: '18/02/25',
    goLive: '31/10/25',
    status: 'b-gl',
    statusLabel: 'Go Live Preparation',
    stage: 'Progress',
  },
];

export const initialInboxItems: InboxItem[] = [
  {
    id: 'D2D-2025-002',
    name: 'SAP S/4HANA Finance Module Upgrade',
    statusLabel: 'Approval In Progress',
    initiator: 'Mohammed Al Ketbi',
    date: '20 January 2025',
    demandData: demands[1],
  },
  {
    id: 'D2D-2025-005',
    name: 'Vendor Management System',
    statusLabel: 'Approval In Progress',
    initiator: 'Rashid Al Maktoum',
    date: '10 December 2024',
    demandData: demands[4],
  },
  {
    id: 'D2D-2025-008',
    name: 'Data Warehouse Modernization',
    statusLabel: 'Approval In Progress',
    initiator: 'Hessa Al Mehairi',
    date: '5 January 2025',
    demandData: demands[7],
  },
];

export const demandTypeInfo = {
  new: {
    tag: 'Turnkey / New Initiative',
    title: 'New System',
    desc: 'For brand-new projects, platforms, or initiatives requiring full lifecycle governance from concept to completion.',
    num: '01',
  },
  enhance: {
    tag: 'Enhancement Request',
    title: 'Enhancement',
    desc: 'For changes, enhancements, or extensions to an existing system — scoped and governed end-to-end.',
    num: '02',
  },
  poc: {
    tag: 'POC / Feasibility',
    title: 'Proof of Concept',
    desc: 'Validate technical feasibility and viability before committing full resources to implementation.',
    num: '03',
  },
};
